spring:
    application:
        name: liquibase-demo

    # Database configuration for Docker Compose PostgreSQL
    datasource:
        url: jdbc:postgresql://localhost:5432/mydatabase
        username: myuser
        password: secret
        driver-class-name: org.postgresql.Driver

    # JPA configuration
    jpa:
        hibernate:
            ddl-auto: validate # Liquibase handles schema
        show-sql: true
    
    # Liquibase configuration
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yaml

# Server Configs
server:
  port: 8080
  servlet:
    context-path: /ecommerce-system

# Swagger Config
springdoc:
  swagger-ui:
    path: /swagger-ui.html 