package com.youssef_gamal.liquibase_demo.mappers;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

import com.youssef_gamal.liquibase_demo.dtos.CustomerDTO;
import com.youssef_gamal.liquibase_demo.entities.Customer;

@Mapper(componentModel = "spring")
public interface CustomerMapper {
    CustomerDTO toDto(Customer customer);
    Customer toEntity(CustomerDTO customerDTO);

    @Mapping(target = "id", ignore = true) // ID is typically generated by DB
    void updateEntityFromDto(CustomerDTO customerDTO, @MappingTarget Customer customer);
}
